export const user = `CREATE TABLE IF NOT EXISTS user (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
hash_password VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)`;
